server:
  port: 8108

spring:
  application:
    name: chat-deepseek

  ai:
    deepseek:
      api-key: ${AI_DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false

logging:
  level:
    root: info
    org.springframework.ai: debug
    io.modelcontextprotocol: debug
    top.lrshuai.ai: info