server:
  port: 8107

spring:
  application:
    name: chat-ollama

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2

logging:
  level:
    root: info
    org.springframework.ai: debug
    io.modelcontextprotocol: debug
    top.lrshuai.ai: info